[tool.poetry]
name = "apis-highlighter"
version = "1.0.0"
description = "Highlighter module for annotations in APIS framework"
authors = ["Matthias Schl√∂gl <m.schloegl@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.6, <3.11"
apis-core = ">=0.16.0"

[tool.poetry.dev-dependencies]
lastversion = "^2.0.1"
dj-database-url = "^0.5.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
