[tool.poetry]
name = "apis-highlighter"
version = "0.9.0"
description = "Highlighter module for annotations in APIS framework"
authors = ["Matthias Schl√∂gl <m.schloegl@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.6, <3.9"
apis-core = "^0.16"

[tool.poetry.dev-dependencies]
lastversion = "^1.3.3"
dj-database-url = "^0.5.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
